### ISSUE TITLE
Unable to send chat messages while incoming message is unconfirmed.

### ISSUE THREAD

**Issue by jdogresorg** [17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod/dropzone_ruby#23]
In testing out the chat interface it appears that you are unable to SEND a outbound chat message while the INCOMING chat message is unconfirmed.

Example: 
I initiated a chat session with junseth a couple days ago... a few minutes ago he ACK'd the request and sent me a message...

```
dropzone chat show <MY_PRIVATE_KEY> 9fb8922974234a5389557a463f73316c357689228692332d20190b46fc30c15d
+------------------------------------------------------------------------+
| Chat: 9fb8922974234a5389557a463f73316c357689228692332d20190b46fc30c15d |
+------------------------------------------------------------------------+
| mjuNSeTHvjiwTXfaSABHenKdAE85pCiM64: Hey handsome.                      |
+------------------------------------------------------------------------+
```

All looks good.. so I try to send him a reply and I get told "Wallet Funds are too low, or no UTXOs are available. Try again in the next confirmation, and/or fund this wallet with more BTC/tBTC and UTXOs"

At the time, his ACK and first chat were still in mempool... unconfirmed
https://gyazo.com/53e7d9c1e1ec88000cab47c3cc2a52bd

```
root@CryptoDevServer:~# dropzone chat say <MY_PRIVATE_KEY> 9fb8922974234a5389557a463f73316c357689228692332d20190b46fc30c15d "testing" --trace
/usr/local/rvm/gems/ruby-2.2.1/gems/dropzone_ruby-0.1.3/lib/dropzone/connection.rb:287:in `allocate_inputs_for': Wallet Funds are too low, or no UTXOs are available. Try again in the next confirmation, and/or fund this wallet with more BTC/tBTC and UTXOs (Dropzone::BitcoinConnection::WalletFundsTooLowOrNoUTXOs)
    from /usr/local/rvm/gems/ruby-2.2.1/gems/dropzone_ruby-0.1.3/lib/dropzone/connection.rb:247:in `create_tx'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/dropzone_ruby-0.1.3/lib/dropzone/connection.rb:175:in `save!'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/dropzone_ruby-0.1.3/lib/dropzone/message_base.rb:39:in `save!'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/dropzone_ruby-0.1.3/lib/dropzone/session.rb:145:in `communicate!'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/dropzone_ruby-0.1.3/lib/dropzone/session.rb:54:in `send'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/dropzone_ruby-0.1.3/lib/dropzone/command.rb:309:in `chat_say'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/command.rb:179:in `call'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /usr/local/rvm/gems/ruby-2.2.1/gems/commander-4.3.5/lib/commander/import.rb:5:in `block in <top (required)>'
```

Once the INCOMING message is written to a block, then I am allowed to send an OUTGOING message. 

We should not have to wait for chat messages to be confirmed before being allowed to respond.... 15 minutes in between chat messages is way too slow.

**Comment by ScroogeMcDuckButWithBitcoin** [comment]
This should be fixed, but I think I'm going to ignore it for now , and focus my effort on the javascript code in this respect. I'll leave this open nonetheless.
